### PR TITLE
PROD-219 Replace Button with Shadcn Button in Reveal

### PR DESCRIPTION
**Pull request by neel-ds**
- Description
Testing Shadcn Button component with two variants in Reveal Dialog

- What are the steps to test that this code is working?
Try to reveal any question 

- Screen shots or recordings for UI changes
Screenshot 2024-09-09 at 12 39 08 PM

### CODE REVIEW

**Comment by Yihwan** [comment]
hi @neel-ds can you add a screenshot of the "after" changes

**Comment by Yihwan** [comment]
hi @neel-ds i think thre might've been a miscommunication; part of the scope of this task is to add the new button styles as shown on this figma page: https://www.figma.com/design/3pZWm9gRbVMnkAfd5zY7GE/Chomp-UI-Shared-Library?node-id=19-582&node-type=FRAME&t=u7ly4HUCprh6onfu-0

**Review by marvinmarnold — APPROVED** [review]

**Comment by marvinmarnold** [comment]
@Yihwan i'll leave to you to approve when colors are sorted out. Things are good for me from code side.

**Comment by marvinmarnold** [comment]
Merging now to unblock other things @Yihwan

**Pull request merged**
