### PR TITLE
PROD-285 Add comments for restore database

### PR DESCRIPTION
**Pull request by neel-ds**
- Description
RFC - Restore database 
Add step by step instructions to restore database from backup file easily

- What are the steps to test that this code is working?
Try restoring local db
- Screen shots or recordings for UI changes
NA

### CODE REVIEW

**Review by yash431garg — COMMENTED** [review]
Can you please add a small comment in script as well to refer to readme?

**Review by yash431garg — APPROVED** [review]

**Review by marvinmarnold — COMMENTED** [review]
I thought there were more substantive changes @AndrejRadomiljac had to do to get things working. I remember this script didn't work immediately. 

Can you try this on the method on the staging DB to make sure it works?

**Comment by neel-ds** [comment]
> I thought there were more substantive changes @AndrejRadomiljac had to do to get things working. I remember this script didn't work immediately.
> 
> Can you try this on the method on the staging DB to make sure it works?

Yash and I tried it locally and included those changes in instructions. It works fine now. Do you want me to try it on staging?

**Review by danijel-radomiljac — APPROVED** [review]

**Comment by neel-ds** [comment]
> Yea, please try on staging, just in case there is something different about that environment.

Just tried restoring in staging, works completely fine. Good to go!

**Pull request merged**
