### PR TITLE
fix: Add sentry capture in share claim all drawer

### PR DESCRIPTION
**Pull request by neel-ds**
- Description
Sometimes share claim all drawer can't fetch the preview link and recently we moved it into try-catch. PR add patch to record that error in Sentry

- What are the steps to test that this code is working?
Verify from Sentry Dashboard after claim all

- Screen shots or recordings for UI changes
NA - Refactor

### CODE REVIEW

**Review by samott — DISMISSED** [review]

**Review by marvinmarnold — COMMENTED** [review]
These changes look good. But can you provide more details about why the share image is failing? We are in control of that image rendering, so errors should be extremely rare.

**Comment by yash431garg** [comment]
> These changes look good. But can you provide more details about why the share image is failing? We are in control of that image rendering, so errors should be extremely rare.

I have seen this image fail locally with ngrock and in the preview environment, showing a request timeout error. I am not sure, but perhaps we are missing some configuration that we are unaware of.

**Comment by marvinmarnold** [comment]
> > These changes look good. But can you provide more details about why the share image is failing? We are in control of that image rendering, so errors should be extremely rare.
> 
> I have seen this image fail locally with ngrock and in the preview environment, showing a request timeout error. I am not sure, but perhaps we are missing some configuration that we are unaware of.

@samott have you seen these failures also?

**Comment by neel-ds** [comment]
> These changes look good. But can you provide more details about why the share image is failing? We are in control of that image rendering, so errors should be extremely rare.

Error [locally]: link-preview-js did not receive a valid a url or text due to localhost so I added cause in Sentry capture for better error handling

**Review by marvinmarnold — APPROVED** [review]

**Pull request merged**
