### PR TITLE
PROD-341: fix login pop up stacks

### PR DESCRIPTION
**Pull request by neel-ds**
- Description
Revert back to #550 and fix loader screen issue on mobile if stack has more decks

The LoginPopup was causing issues on the stack page for mobile screens, so you temporarily commented it out during Breakpoint. This PR resolves the issue by disabling an initial isLoading state in LoginPopup and reverting the original behavior of triggering on deck click.

- What are the steps to test that this code is working?
Open Engima stack in mobile to test the consistency

- Screen shots or recordings for UI changes
NA

### CODE REVIEW

**Review by marvinmarnold — COMMENTED** [review]
Could you add more details to your PR description? What was the root cause and how does this change fix it?

**Comment by neel-ds** [comment]
> Could you add more details to your PR description? What was the root cause and how does this change fix it?

The LoginPopup was causing issues on the stack page for mobile screens, so you temporarily commented it out during Breakpoint. This PR resolves the issue by disabling an initial isLoading state in LoginPopup and reverting the original behavior of triggering on deck click.

**Review by danijel-radomiljac — APPROVED** [review]

**Comment by marvinmarnold** [comment]
> This PR resolves the issue by disabling an initial isLoading state in LoginPopup and reverting the original behavior of triggering on deck click.

it's not obvious to me why the wrong isLoading initial state was causing the slow behavior on mobile. Can you explain the bug a little more.

**Comment by neel-ds** [comment]
> it's not obvious to me why the wrong isLoading initial state was causing the slow behavior on mobile. Can you explain the bug a little more.

@marvinmarnold  The isLoading state in LoginPopUp was displaying LoaderScreen while fetching authToken and awaitSignatureState from dynamicContext. Since this is inside a useEffect, it could trigger validation multiple times as the context changes. I turned off the initial isLoading state to prevent the loader screen from appearing unnecessarily when the user is on the stack page without interacting with a deck.

https://github.com/gator-labs/chomp/blob/2a9ba15fa908e253de9d7bc4c308f72ffb02c9d5/app/components/LoginPopUp/LoginPopUp.tsx#L61

**Comment by danijel-radomiljac** [comment]
I will close this PR because I will create a new one. I think I found where the problem was.

**Pull request closed without merging**
