### PR TITLE
Feat/home stats

### PR DESCRIPTION
**Pull request by AnteVuletic**
- Description:
This PR adds the new statistics widget in the homepage.
- ClickUp links:
https://app.clickup.com/t/86byrw52w
https://app.clickup.com/t/86byn521v

- What are the acceptance criteria? What are the steps to test that this code is working?

1. If there's no questions answered stats should show default values of 0 or "-" for time
2. If a question or card is answered it should count as 1 card chomped
3. If a question or card is answered the average time to answer should appear
4. If user answers two days in a row the streak should jump to 2, given the user does not answer the next day it remains at 2. 
5. If the user answers 3 days in a row in the future the streak will increment to 3. 
6. Points are just shown from the old feature in the db

### CODE REVIEW

**Comment by marvinmarnold** [comment]
I'm getting an error on this preview link: https://chomp-git-feat-home-stats-gator-labs.vercel.app/application

Screenshot 2024-05-17 at 12 29 10 PM

It's happening immediately after login. Refresh doesn't work.

**Comment by AnteVuletic** [comment]
@marvinmarnold migrations are not applied automatically, @bdeak4 can you do something about this?

**Comment by AnteVuletic** [comment]
> I'm getting an error on this preview link: https://chomp-git-feat-home-stats-gator-labs.vercel.app/application
> 
> Screenshot 2024-05-17 at 12 29 10 PM
> 
> It's happening immediately after login. Refresh doesn't work.

You can try locally for the time being

**Comment by marvinmarnold** [comment]
Please let me know if this starts blocking other work @AnteVuletic. Otherwise I'll wait for @bdeak4 to fix the build so I can test live.

**Review by marvinmarnold — APPROVED** [review]
Will test once deployed

**Pull request merged**
