### PR TITLE
Prod 328: fix editing decks

### PR DESCRIPTION
**Pull request by yash431garg**
- Description
1. Remove questin from deck
2. Don't allow edit if deck has more than one answer
- What are the steps to test that this code is working?
1. Edit and delete functionality in created deck with no question answers

### CODE REVIEW

**Review by marvinmarnold — COMMENTED** [review]
During our meeting today, let's talk about adding unit tests for this.

**Comment by yash431garg** [comment]
> During our meeting today, let's talk about adding unit tests for this.

Sure,

**Comment by marvinmarnold** [comment]
@yash431garg there are conflicts fyi

**Comment by yash431garg** [comment]
> @yash431garg there are conflicts fyi

Yup, will resolve them.

**Pull request closed without merging**
