### PR TITLE
PROD-135: Shadcn customized alert component

### PR DESCRIPTION
**Pull request by yash431garg**
- Description
Shared customized alert component. 
- What are the steps to test that this code is working?
New alert dialog on Deck 
- Screen shots or recordings for UI changes
Screenshot 2024-09-09 at 1 10 45 PM

Additonal Notes: Primary button will be automaticaly be changed to the default varient when this PROD-219 will be merged.

### CODE REVIEW

**Comment by Yihwan** [comment]
added some design review comments in the deploy preview. i am also noticing a bug where clicking "proceed" after timer runs out does not close dialog when it goes to the next question. unsure if this is artifact of deploy preview env but should double check. 

https://github.com/user-attachments/assets/c1239ee9-3edc-448d-9fb6-442e2d19138b

**Comment by yash431garg** [comment]
@Yihwan I am fixing the design request meanwhile I find out that the bug you mentioned exist in our production PWA as well. I think it is better if we can create a seperate ticket for the bug. 

https://github.com/user-attachments/assets/c263d87f-e745-4454-99db-ec04b98b15f5

**Comment by yash431garg** [comment]
@Yihwan Can you please review the updated design changes?

**Comment by Yihwan** [comment]
Screenshot 2024-09-10 at 10 32 40

still only seeing 12px top margin above description when mocks specify 24px

**Review by Yihwan — APPROVED** [review]
can merge after margin change

**Comment by yash431garg** [comment]
@Yihwan, sorry for the confusion earlier. I misinterpreted the 24px value, but I've just updated the code now.

**Pull request merged**
