### PR TITLE
PROD-80 updated profile page

### PR DESCRIPTION
**Pull request by AndrejRadomiljac**
✅ Add Linear ID (e.g., `PROD-123`) to PR title to automatically link issue
Link to the Linear https://linear.app/gator/issue/PROD-80/first-pass-on-profile-page
- Description
- UI and content updates. Added possibility to remove image (sets our default avatar image) on click
- What are the steps to test that this code is working?
- Screen shots or recordings for UI changes
New profile setting page
Screenshot 2024-08-29 at 02 08 52

### CODE REVIEW

**Comment by marvinmarnold** [comment]
Code lgtm. Will let @Yihwan approve.

**Review by Yihwan — CHANGES_REQUESTED** [review]
IMG_0647
* i am still getting zoomed in on mobile in-app phantom browser. input font size may need to be adjusted to prevent this accessibility feature.
* the X icon next to profile picture is too close to the edit profile tap target. clicking on the X currently opens up the edit modal. please place X in upper right hand corner of containing rectangle for now (and hide if user has not selected profile pic). we can revisit placement later. 
* clicking "Go home" from the unsaved changes modal results in 404

**Comment by AndrejRadomiljac** [comment]
> IMG_0647
> 
> * i am still getting zoomed in on mobile in-app phantom browser. input font size may need to be adjusted to prevent this accessibility feature.
> * the X icon next to profile picture is too close to the edit profile tap target. clicking on the X currently opens up the edit modal. please place X in upper right hand corner of containing rectangle for now (and hide if user has not selected profile pic). we can revisit placement later.
> * clicking "Go home" from the unsaved changes modal results in 404

I checked 404. The redirect is setup correctly to /application as it is required. I think this is preview thing, but I'll check once again. Will see what I can do with this "zoomed in" thing.

**Comment by AndrejRadomiljac** [comment]
> IMG_0647
> 
> * i am still getting zoomed in on mobile in-app phantom browser. input font size may need to be adjusted to prevent this accessibility feature.
> * the X icon next to profile picture is too close to the edit profile tap target. clicking on the X currently opens up the edit modal. please place X in upper right hand corner of containing rectangle for now (and hide if user has not selected profile pic). we can revisit placement later.
> * clicking "Go home" from the unsaved changes modal results in 404

Go Home redirection local behaviour
https://github.com/user-attachments/assets/892ad445-c08e-4db0-97ae-5a4a17350ce8

**Review by Yihwan — APPROVED** [review]
wont have time to fully test again but trust that the changes are good to go and we can address any further ones in future PRs 👍

**Pull request merged**
