### PR TITLE
Prod 193/enable navbar dailydeck

### PR DESCRIPTION
**Pull request by yash431garg**
✅ Add Linear ID (e.g., `PROD-123`) to PR title to automatically link issue

- Description
1. User can skip daily deck and it will be shown in the expiring soon section user can access it again from there.
- What are the steps to test that this code is working?
Able to skip daily deck and open again from the expiring soon section.
- Screen shots or recordings for UI changes
Screenshot 2024-09-10 at 8 06 30 PM
Screenshot 2024-09-10 at 8 06 42 PM

### CODE REVIEW

**Review by marvinmarnold — APPROVED** [review]
@yash431garg this looks great to me.

@Yihwan how do we want to record QuestionAnswer.status that are not answered because the user clicks home? Some options 'Viewed', 'Skipped', 'Exited'. Currently, this PR uses QuestionAnswer.status = Viewed for this case.

**Comment by Yihwan** [comment]
> @yash431garg this looks great to me.
> 
> @Yihwan how do we want to record QuestionAnswer.status that are not answered because the user clicks home? Some options 'Viewed', 'Skipped', 'Exited'. Currently, this PR uses QuestionAnswer.status = Viewed for this case.

happy to defer to devs on this since i don't have a specific ask in mind right now. if there is a specific ask later (e.g., we want to differentiate between exit actions for analytics purposes) i can submit a new task if that works

**Review by Yihwan — CHANGES_REQUESTED** [review]
hi im not able to recreate desird functionality. clicking home seems to take me to the next question despite not answering a question

https://github.com/user-attachments/assets/5472f1f3-a771-41c4-974c-470017ec2264

**Comment by marvinmarnold** [comment]
There's a different issue preventing me from testing a second time. I think because I already answered a daily deck today then created another, it now thinks I've already answered the second deck? I don't think we would expect to see two daily decks in prod but can you look into this behavior?


https://github.com/user-attachments/assets/355b48fa-a344-44c1-ba64-93eb1b0e28ce

**Comment by marvinmarnold** [comment]
@Yihwan can you please test this again? The expected behavior is a little different than what's on Linear. Users are auto redirected to complete daily deck if they have not seen any of the questions. Otherwise, it will only show up in expiring soon. Regardless of refreshing, etc.

**Comment by marvinmarnold** [comment]
@yash431garg can you fix conflicts?

**Pull request merged**
