### PR TITLE
fix: flaky tests

### PR DESCRIPTION
**Pull request by neel-ds**
- Description
Fix some flaky tests by adding retry mock
- What are the steps to test that this code is working?
NA
- Screen shots or recordings for UI changes
NA

### CODE REVIEW

**Comment by marvinmarnold** [comment]
@neel-ds can you disable the failing deck test? @danijel-radomiljac can go back later and figure out why it keeps breaking as part of https://linear.app/gator/issue/PROD-511/flaky-deck-tests

**Comment by marvinmarnold** [comment]
Oh I see it passed now. Do you know why? Did you delete entries from demo?

**Comment by neel-ds** [comment]
> @neel-ds can you disable the failing deck test? @danijel-radomiljac can go back later and figure out why it keeps breaking as part of https://linear.app/gator/issue/PROD-511/flaky-deck-tests

This test works fine locally, even when run concurrently. I re-ran the action, and it now works as expected. I also reviewed the test again to see if any changes were needed from our end, but everything looks good to me.

**Comment by neel-ds** [comment]
> Oh I see it passed now. Do you know why? Did you delete entries from demo?

yeah it could be due to duplicate entries but now it's resolved as it delete entries after each test.

**Review by marvinmarnold — APPROVED** [review]
Ok we can merge this, but I'm not convinced it's enough. Next step after merging this is to update all current PRs and get tests passing. I don't want to have to rerun each multiple times for the tests to pass.

If decks test is still known to be flaky, lets deactivate and fix it separately.

**Comment by neel-ds** [comment]
> Ok we can merge this, but I'm not convinced it's enough. Next step after merging this is to update all current PRs and get tests passing. I don't want to have to rerun each multiple times for the tests to pass.
> 
> If decks test is still known to be flaky, lets deactivate and fix it separately.

I agree with you. If we see deck test fail again then we will deactivate it.

**Pull request merged**
