### PR TITLE
PROD-533/reveal-check-for-low-sol-balance 

### PR DESCRIPTION
**Pull request by danijel-radomiljac**

### CODE REVIEW

**Review by marvinmarnold — CHANGES_REQUESTED** [review]
We have an Insufficient Balance state that shows up for BONK. In addition to the changes you already made, can you detect low SOL balance and display the same state?

Screenshot 2024-12-11 at 1 23 40 PM

**Comment by marvinmarnold** [comment]
Left comment in linear: https://linear.app/gator/issue/PROD-533/reveal-check-for-low-sol-balance#comment-faf8582f

**Review by yash431garg — APPROVED** [review]
LGTM

**Review by marvinmarnold — CHANGES_REQUESTED** [review]
I dropped a recording and comment here about long loading time: https://linear.app/gator/issue/PROD-533/reveal-check-for-low-sol-balance

**Review by samott — DISMISSED** [review]

**Pull request merged**
