### PR TITLE
PROD-281: Update tailwind config

### PR DESCRIPTION
**Pull request by neel-ds**
- Description
Added the remaining color primitives to `tailwind.config.ts` and ensure the component colors stay consistent after these changes
- What are the steps to test that this code is working?
Test the preview for style consistency
- Screen shots or recordings for UI changes
Screenshot 2024-09-12 at 1 38 33 AM
Screenshot 2024-09-12 at 1 39 09 AM

### CODE REVIEW

**Comment by Yihwan** [comment]
defer to @gatorthana on design review for this one

**Review by gatorthana — CHANGES_REQUESTED** [review]
1. "next" button still seem to use old color


image

**Comment by neel-ds** [comment]
@gatorthana I haven't changed the button throughout the app. I will create follow up ticket to replace existing components with new shadcn one. This PR mainly focus on color which I replaced here: 
https://github.com/gator-labs/chomp/pull/487/files#diff-655dc9e3d0aa561e3fa164bf48bd89cb0f5da65e0a567f8ebbf9dd791a0e7f40

**Comment by gatorthana** [comment]
Ah, okay, sounds good @neel-ds !

**Pull request merged**
