### PR TITLE
PROD-295: campaign decks cleanup

### PR DESCRIPTION
**Pull request by yash431garg**
- Description
1. Added route back to campaign on specific campaign page
2. Udated campaign image as fallback image and set default to deck image.
- What are the steps to test that this code is working?
1. Redirecting back to campaigns from /campaigns/{campaignsId}
2. Verifying decks images on /campaigns/{campaignsId}

### CODE REVIEW

**Review by marvinmarnold — CHANGES_REQUESTED** [review]
Deck does not have image, but does belong to a campaign. But campaign image not showing: https://chomp-6794mhdwn-gator-labs.vercel.app/application/decks/238

**Comment by yash431garg** [comment]
@marvinmarnold If I am not wrong here from the ticket that changes are related to this page /campaigns/1. Showing deck image if there is one otherwise show campign image is added in this file app/campaigns/[id]/page.tsx. 

Screenshot 2024-09-18 at 3 52 57 PM

**Comment by marvinmarnold** [comment]
> @marvinmarnold If I am not wrong here from the ticket that changes are related to this page /campaigns/1. Showing deck image if there is one otherwise show campign image is added in this file app/campaigns/[id]/page.tsx.

@yash431garg yes you are correct I didn't realize the original scope. Would you mind implementing the same logic on the deck info card page /application/decks/ID also?

**Comment by yash431garg** [comment]
> > @marvinmarnold If I am not wrong here from the ticket that changes are related to this page /campaigns/1. Showing deck image if there is one otherwise show campign image is added in this file app/campaigns/[id]/page.tsx.
> 
> @yash431garg yes you are correct I didn't realize the original scope. Would you mind implementing the same logic on the deck info card page /application/decks/ID also?

Sure I will check that out. But I have a doubt images in the campigns are necassary to create it. But in deck it is optional let's say if the deck isn't related to any campaign and deck also doesn't have a image. What we have to do in that case?

**Comment by marvinmarnold** [comment]
> > > @marvinmarnold If I am not wrong here from the ticket that changes are related to this page /campaigns/1. Showing deck image if there is one otherwise show campign image is added in this file app/campaigns/[id]/page.tsx.
> > 
> > 
> > @yash431garg yes you are correct I didn't realize the original scope. Would you mind implementing the same logic on the deck info card page /application/decks/ID also?
> 
> Sure I will check that out. But I have a doubt images in the campigns are necassary to create it. But in deck it is optional let's say if the deck isn't related to any campaign and deck also doesn't have a image. What we have to do in that case?

Good question. In the case where there is no deck image or campaign image, it is fine to not show any image.

**Comment by yash431garg** [comment]
> > > > @marvinmarnold If I am not wrong here from the ticket that changes are related to this page /campaigns/1. Showing deck image if there is one otherwise show campign image is added in this file app/campaigns/[id]/page.tsx.
> > > 
> > > 
> > > @yash431garg yes you are correct I didn't realize the original scope. Would you mind implementing the same logic on the deck info card page /application/decks/ID also?
> > 
> > 
> > Sure I will check that out. But I have a doubt images in the campigns are necassary to create it. But in deck it is optional let's say if the deck isn't related to any campaign and deck also doesn't have a image. What we have to do in that case?
> 
> Good question. In the case where there is no deck image or campaign image, it is fine to not show any image.

@marvinmarnold I have added the changes you mentioned in the PR mentioned below. The reason behined that was there were already changes related to campaign. So, it was easier to handle it there. 

PR: https://github.com/gator-labs/chomp/pull/530

**Pull request merged**
