### PR TITLE
Prod 235/new toast messages design

### PR DESCRIPTION
**Pull request by AndrejRadomiljac**
✅ Add Linear ID (e.g., `PROD-123`) to PR title to automatically link issue
Link to the linear https://linear.app/gator/issue/PROD-235/toast-designs
- Description
- The only thing that is not updated is spinner since I could not find the animation part. All other toast are updated.
- What are the steps to test that this code is working?
- Try to edit profile things, force the validation error. Reveal question, claim functionality
- Screen shots or recordings for UI changes

### CODE REVIEW

**Comment by marvinmarnold** [comment]
@Yihwan @gatorthana please review

**Review by gatorthana — CHANGES_REQUESTED** [review]
I couldn't get "Loading" and "Info" variations to appear, but otherwise looks good to me.

Requesting one change

1. the bottom purple line is supposed to be a countdown, so it should appear as a full bar of purple (as is), and it should retract left until it's gone, and the toast should auto dismiss.

Attaching screenshots just to s
Screenshot 2024-09-13 at 12 03 02 PM
Screenshot 2024-09-13 at 12 03 27 PM
Screenshot 2024-09-13 at 12 03 56 PM
how what it currently looks like on my device.

**Comment by marvinmarnold** [comment]
@AndrejRadomiljac there's a conflict fyi

**Comment by AndrejRadomiljac** [comment]
> @AndrejRadomiljac there's a conflict fyi

Sorry, will resolve it.

**Review by gatorthana — APPROVED** [review]

**Pull request merged**
